### PR TITLE
D8NID-382 Replace file/image fields with entity reference fields

### PR DESCRIPTION
**Pull request by johangant**
Large PR (sorry!) that in essence covers config for a few key things:

1. View modes for media entities (embed, preview) for WYSIWYG display and entity browser widget preview respectively.
2. Configured display modes for the above view modes, for each media entity type.
3. Views displays to power the media entity type browsers (allows you to look for media).
4. Entity browsers for each media type (in favour of a single, generic one).
5. Entity embed buttons to glue together CKEditor and the entity browsers.
6. CKEditor profile config to add buttons above to the basic and full HTML profiles.
7. Field storage/instance config to replace the image/file fields with entity reference fields; same cardinality and help text.
8. Form display widget config for the entity browser widgets used by the fields above.

General ethos in this major PR is consistency and clarity over brevity. That means:

- No single, general, cluttered media browser to span all types.
- Simple button text (select, save) and consistent labels over more verbose and variable ones.
- Entity browsers show browser first, to encourage content re-use over creation.
- CKeditor has embed buttons per media type rather than a single, generic button.

Some gotchas:

- Entity embed buttons need high res PNG or SVG icons. These are stored in the DB so need to be added as content rather than code.
- Locations are, essentially, paragraphs bundles with a geolocation field attached. The entity browser only allows you to create new 'Map' bundles as re-use of locations is probably minimal.
- Paragraphs embedding runs a bit at odds with the entity browser steps, so the UX is a bit flaky although perfectly functional.

### CODE REVIEW

**Comment by johangant** [comment]
Adding quite a few folks to review. Might be as easy to demo this at some point?

**Comment by johangant** [comment]
Applying the config changes over a db already full of content is likely to cause a few headaches, so this will likely require a fresh install from config + re-import of source content to produce a db dump for the wider team to use day-to-day.

**Comment by johangant** [comment]
Turns out `drush cim` will work. It bails out early on a few minor/quirky issues, but re-running seems to get 99% of things to stick, even with existing content. That's pretty epic configuration management given the seismic nature of the changes here.

**Comment by omahm** [comment]
> Turns out `drush cim` will work. It bails out early on a few minor/quirky issues, but re-running seems to get 99% of things to stick, even with existing content. That's pretty epic configuration management given the seismic nature of the changes here.

I'm amazed with all those changes there aren't more issues with existing content.

**Comment by johangant** [comment]
> > Turns out `drush cim` will work. It bails out early on a few minor/quirky issues, but re-running seems to get 99% of things to stick, even with existing content. That's pretty epic configuration management given the seismic nature of the changes here.
> 
> I'm amazed with all those changes there aren't more issues with existing content.

I know, same here! I'd be inclined to import from fresh and re-migrate, then produce a fresh db export to avoid any niggly hangovers. I had some entity browser config that claimed it wasn't fully up to date but clearly was when I inspected it, even after multiple import attempts. Not critical, but a bit weird.

**Comment by omahm** [comment]
> > > Turns out `drush cim` will work. It bails out early on a few minor/quirky issues, but re-running seems to get 99% of things to stick, even with existing content. That's pretty epic configuration management given the seismic nature of the changes here.
> > 
> > 
> > I'm amazed with all those changes there aren't more issues with existing content.
> 
> I know, same here! I'd be inclined to import from fresh and re-migrate, then produce a fresh db export to avoid any niggly hangovers. I had some entity browser config that claimed it wasn't fully up to date but clearly was when I inspected it, even after multiple import attempts. Not critical, but a bit weird.

If you're going down the fresh install and migrate I'd restart docker first. Looks like we have some niggles with core pathalias dependencies too.

**Pull request merged**
