### PR TITLE
D8NID-921 ~ Elevated Solr ID config

### PR DESCRIPTION
**Pull request by omahm**

### CODE REVIEW

**Comment by johangant** [comment]
Great stuff, I think I can see how this works. What picks up the YML files, is it how search API already handles things?

**Comment by omahm** [comment]
> Great stuff, I think I can see how this works. What picks up the YML files, is it how search API already handles things?

They're config entities, this is simply importing them.

**Review by johangant — APPROVED** [review]
Good stuff, let's get it in the build 👍

**Review by DuttonMa — APPROVED** [review]
Looks good

**Pull request merged**
