### PR TITLE
Remove schema metatags for medical conditions

### PR DESCRIPTION
**Pull request by johangant**
Patch isn't fully stable with 2.1 release, causing fatal exceptions in other parts of the build

### CODE REVIEW

**Comment by DuttonMa** [comment]
So what do we need to do here? Do we need to create another patch to replace the one that is being removed?

**Comment by johangant** [comment]
> So what do we need to do here? Do we need to create another patch to replace the one that is being removed?

That's the idea, but that task has been split into its own ticket as it's fairly self-contained. The wider schema_metatags functionality is useful to keep in.

**Comment by omahm** [comment]
> > So what do we need to do here? Do we need to create another patch to replace the one that is being removed?
> 
> That's the idea, but that task has been split into its own ticket as it's fairly self-contained. The wider schema_metatags functionality is useful to keep in.

Might also need to look at how this affects taxonomy terms.

**Comment by johangant** [comment]
> Might also need to look at how this affects taxonomy terms.

Reviewed against the original bug reported and can confirm this solves that issue. There shouldn't be any extra metatags set by this module for terms but I think it tickled the bug when it tried to load defaults with the entity (or related hooks) when requesting the taxonomy term edit form. Either way, this looks like a safe merge until the medical condition patch can be re-rolled.

**Review by omahm — APPROVED** [review]
👍

**Pull request merged**
