### PR TITLE
Blocks config for recipe sidebar

### PR DESCRIPTION
**Pull request by johangant**
Provides some useful starting config for Bartik theme. This will, of course, change once the nidirect theme matures.

### CODE REVIEW

**Comment by johangant** [comment]
Yep, this is pitching for the state the project is in today rather than what it needs to be once the nidirect theme is ready enough to evaluate this with.

So options are: I can hold back this PR until the nidirect theme is more mature and there's a clear region to set this to. Or this can merge and create a new PR to adjust the config to fit the nidirect theme when it's ready.

Thoughts?

**Comment by omahm** [comment]
> Yep, this is pitching for the state the project is in today rather than what it needs to be once the nidirect theme is ready enough to evaluate this with.
> 
> So options are: I can hold back this PR until the nidirect theme is more mature and there's a clear region to set this to. Or this can merge and create a new PR to adjust the config to fit the nidirect theme when it's ready.
> 
> Thoughts?

I'd mark this ticket as blocked, link it to a theming request ticket and keep the PR open as a reminder that functionality is reliant on the theme work progressing.

**Comment by johangant** [comment]
Sounds fine to me. I'll do that and label this PR as well, cheers.

**Comment by johangant** [comment]
Redundant, superseded by https://github.com/dof-dss/nidirect-drupal/pull/55

**Pull request closed without merging**
